version: '3.8'

services:
  app:
    build: .
    container_name: fleettrack-backend
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fleettrack-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fleettrack
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
